### ISSUE TITLE
server crashes randomly when using waystone

### ISSUE THREAD

**Issue by youjin3167** [Filostorm/Multiblock-Madness#143]
first there was a crash when opened the Tinkers crafting table, and now the server crashes randomly when using waystone
I'm bad with english, sorry for using translator

this is crash reports

Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1493)
	at net.minecraft.entity.EntityTracker.sendLeashedEntitiesInChunk(EntityTracker.java:386)
	at.net.minecraft.server.management.PlayerChunkMapEntry.sendToPlayers(PlayerChunkMapEntry.java:162)
	at.net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:165)
	at.net.minecraft.world.WorldServer.tick(WorldServer.java:227)
	at.net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
	at.net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
	at.net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at.net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by shawn1368** [comment]
Could you send the full crash report?

**Comment by youjin3167** [comment]
[crash-2022-07-23_22.33.47-server.txt](https://github.com/Filostorm/Multiblock-Madness/files/9269953/crash-2022-07-23_22.33.47-server.txt)
