### ISSUE TITLE
Error latest version 1.0.0

### ISSUE THREAD

**Issue by Zonaza** [Filostorm/Multiblock-Madness#21]
**latest.log**

> [02:29:57] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[02:29:57] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[02:29:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[02:29:57] [main/INFO]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[02:29:57] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Zanoza\Twitch\Minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy
[02:29:58] [main/INFO]: Searching C:\Users\Zanoza\Twitch\Minecraft\Instances\Multiblock Madness\mods for mods
[02:29:58] [main/INFO]: Searching C:\Users\Zanoza\Twitch\Minecraft\Instances\Multiblock Madness\mods\1.12.2 for mods
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AdvancedRocketry-1.12.2-1.7.0-240-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod AdvancedRocketryPlugin (zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Apotheosis-1.12.2-1.12.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod ApotheosisCore (shadows.ApotheosisCore) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.4.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[02:29:58] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from arcanearchives-0.2.0.25-mixins8.jar
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.27.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/INFO]: [AstralCore] Initialized.
[02:29:58] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in botaniatweaks-1.9.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod Botania Tweaks Core (quaternary.botaniatweaks.asm.BotaniaTweakerPlugin) is not signed!
[02:29:58] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.10.47_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in cxlibrary-1.12.1-1.6.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod cubex2.cxlibrary.CoreModLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod CXLibraryCore (cubex2.cxlibrary.CoreModLoader) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in engineers_doors-1.12.2-0.9.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod EngineersDoorsLoadingPlugin (nihiltres.engineersdoors.common.asm.EngineersDoorsLoadingPlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in EntityCulling-1.12.2-4.1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod EntityCullingPlugin (meldexun.entityculling.plugin.EntityCullingPlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in fluiddrawers-1.12.2-1.0.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod xyz.phanta.fluiddrawers.coremod.FluidDrawersCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod FluidDrawersCoreMod (xyz.phanta.fluiddrawers.coremod.FluidDrawersCoreMod) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.11-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod com.endertech.minecraft.forge.coremod.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod CorePlugin (com.endertech.minecraft.forge.coremod.CorePlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HammerLib-1.12.2-2.0.6.26.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HardcoreDarkness-MC1.12.2-2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.9.1-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.0-pre327_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[02:29:58] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.3.390.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[02:29:58] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from MixinBootstrap-1.0.5.jar
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in NotEnoughIDs-1.5.4.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod ru.fewizz.neid.asm.Plugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod Plugin (ru.fewizz.neid.asm.Plugin) is not signed!
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: The coremod OTGCorePlugin (com.pg85.otg.forge.asm.excluded.launch.OTGCorePlugin) is not signed!
[02:29:58] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from particleculling-1.12.2-v1.0.1.jar
[02:29:58] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from performant-1.12.2-1.10.jar
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[02:29:58] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in RandomThings-MC1.12.2-4.2.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:58] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:58] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.77.jar
[02:29:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ThaumicAugmentation-1.12.2-2.0.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[02:29:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
[02:29:59] [main/WARN]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[02:29:59] [main/WARN]: The coremod IELoadingPlugin (blusunrize.immersiveengineering.common.asm.IELoadingPlugin) is not signed!
[02:29:59] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
[02:29:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:29:59] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ClassFormatError: Invalid length 26 in LocalVariableTable in class file org/spongepowered/asm/launch/platform/MixinPlatformAgentFMLLegacy
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName0(Native Method)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName(Class.java:348)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.findClass(MixinServiceLaunchWrapper.java:304)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinServiceAbstract.getServiceAgents(MixinServiceAbstract.java:194)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinServiceAbstract.getSideName(MixinServiceAbstract.java:172)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.MixinEnvironment$Side$2.detect(MixinEnvironment.java:180)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.MixinEnvironment.getSide(MixinEnvironment.java:1174)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.MixinEnvironment.printHeader(MixinEnvironment.java:973)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.MixinEnvironment.<init>(MixinEnvironment.java:966)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.MixinEnvironment$Phase.getEnvironment(MixinEnvironment.java:152)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.MixinEnvironment.getEnvironment(MixinEnvironment.java:1357)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.MixinEnvironment.init(MixinEnvironment.java:1336)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:148)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[02:29:59] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Filostorm** [comment]
Did you figure it out?
